### ISSUE TITLE
2 New Useful Commands

### ISSUE THREAD

**Issue by MrGforces** [stageosu/Kaguya#143] opened 2020-11-09 08:13 UTC
I think we need "$googlesearch/$google" command, so we don't waste our time search on the real google when we need it on discord. And "$translate" command will be great too! When we meet someone that can't speak english, we can just use it and allowed to talk with them :)

Hopefully it was good ;)

**Comment by hburn7** [comment] 2020-11-09 14:16
Duplicate of #117

**Closed as completed** 2020-11-09 14:17 UTC

**Comment by hburn7** [comment] 2020-11-09 14:18
I will also say I probably won't implement $translate just because I don't think it will be used.
